services:
  - type: web
    name: raju-transport
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: BASE_URL
        sync: false
